### ISSUE TITLE
Laravel 10 Support

### ISSUE THREAD

**Issue by gregpriday** [suitmedia/laravel-cloudflare#2]
Thanks for creating this pacakge. I was about to create my own, but then I came across yours. Could you add Laravel 10 support?

Alternatively, I could submit a PR. It might just be a `composer.json` change.

**Comment by richan-fongdasen** [comment]
Thank you for reminding me about the latest Laravel version's support. I have just released a new version that addresses the issue. I hope it can be helpful to you. Thank you for using the package.

**Comment by gregpriday** [comment]
That was fast, thanks.
